// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using finjob_backend.Data;

#nullable disable

namespace finjob_backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("finjob_backend.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Scale")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Companys");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 2, 20, 16, 22, 12, 328, DateTimeKind.Local).AddTicks(7186),
                            Description = "None",
                            ImageURL = "https://itviec.com/rails/active_storage/representations/proxy/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1lxREE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d01c8dc918133b1b89705dc00ef4f490b78d20e3/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCem9MWm05eWJXRjBTU0lJY0c1bkJqb0dSVlE2RkhKbGMybDZaVjkwYjE5c2FXMXBkRnNIYVFJc0FXa0NMQUU9IiwiZXhwIjpudWxsLCJwdXIiOiJ2YXJpYXRpb24ifX0=--492f60b9aac6e8159e50e72bb289c5feb47a79d4/mgm-technology-partners-vietnam-logo.png",
                            Location = "Da Nang",
                            Name = "MGM",
                            Scale = "50 - 150 Employees",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 2, 20, 16, 22, 12, 328, DateTimeKind.Local).AddTicks(7199),
                            Description = "None",
                            ImageURL = "https://dsa.org.vn/wp-content/uploads/2018/01/Agility.jpg",
                            Location = "Da Nang",
                            Name = "Agility",
                            Scale = "50 - 100 Employees",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 2, 20, 16, 22, 12, 328, DateTimeKind.Local).AddTicks(7201),
                            Description = "None",
                            ImageURL = "https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/2c47b1dbc75d6d9184be768c39fb9ac7.png",
                            Location = "Da Nang",
                            Name = "Orient",
                            Scale = "20 - 50 Employees",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2023, 2, 20, 16, 22, 12, 328, DateTimeKind.Local).AddTicks(7204),
                            Description = "None",
                            ImageURL = "https://doanhnghiep.quocgiakhoinghiep.vn/wp-content/uploads/2020/08/images-7.png",
                            Location = "Da Nang",
                            Name = "KMS",
                            Scale = "40 - 100 Employees",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2023, 2, 20, 16, 22, 12, 328, DateTimeKind.Local).AddTicks(7205),
                            Description = "None",
                            ImageURL = "https://static.topcv.vn/company_logos/bUsiw4xpTeqvyGecqSrVW3Zuq0dayRwK_1656588043____83f8efe4285d433505271ef261179f41.jpeg",
                            Location = "Da Nang",
                            Name = "NFQ",
                            Scale = "20 - 80 Employees",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
